### ISSUE TITLE
dam_utils.h not found

### ISSUE THREAD

**Issue by bnuastro** [damonge/LimberJack#1]
Dear Damonge,
Sorry to bother you. I would like to run your code but I can not find the head file dam_utils.h.
Could you add this file to repository as well?
Thanks so much!
Best,
Albert

**Comment by damonge** [comment]
Hi,

I wasn't aware anyone was using this. dam_utils is my own utilities library. I've removed the need to use it, so you should be able to compile without it now. Note that you'll need cosmomad, which is another of my repositories. Also, this is a code I've been playing around with, so I won't guarantee that everything in it is 100% correct :-).

Cheers,

David
