### ISSUE TITLE
compiling error cosmo_mad.h not found

### ISSUE THREAD

**Issue by MarkusMichaelRau** [damonge/LimberJack#2]
Hi, 

I'm trying to use your code but I get a compiling error:

gcc -Wall -O3  -I./src -I/usr/include   -c src/common.c -o src/common.o
In file included from src/common.c:1:0:
src/common.h:12:23: schwerwiegender Fehler: cosmo_mad.h: Datei oder Verzeichnis nicht gefunden
 #include "cosmo_mad.h"
                       ^
Kompilierung beendet.
Makefile:39: recipe for target 'src/common.o' failed
make: **\* [src/common.o] Error 1

Is this an external dependency or just a file that is not included in the package?

Cheers,

Markus

**Comment by damonge** [comment]
Hi Markus,

I'm afraid so, you should install this library:
https://github.com/damonge/CosmoMAD

Let me know if you have any trouble with this.

Cheers,

David
